-- Create the ai_assistant_logs table to store interactions with the AI assistant
CREATE TABLE IF NOT EXISTS public.ai_assistant_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamptz NOT NULL DEFAULT now(),
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    user_message text NOT NULL,
    assistant_message text NOT NULL,
    user_type text NOT NULL CHECK (user_type IN ('startup', 'investor', 'unknown')),
    rating smallint CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5))
);

-- Enable RLS
ALTER TABLE public.ai_assistant_logs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies (if they exist) and recreate them

-- Policy: Users can only see their own logs
DROP POLICY IF EXISTS "Users can view their own logs" ON public.ai_assistant_logs;
CREATE POLICY "Users can view their own logs" 
ON public.ai_assistant_logs
FOR SELECT 
USING (auth.uid() = user_id);

-- Policy: Users can only insert their own logs
DROP POLICY IF EXISTS "Users can insert their own logs" ON public.ai_assistant_logs;
CREATE POLICY "Users can insert their own logs" 
ON public.ai_assistant_logs
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Policy: Users can only update their own logs (for ratings)
DROP POLICY IF EXISTS "Users can update their own logs" ON public.ai_assistant_logs;
CREATE POLICY "Users can update their own logs" 
ON public.ai_assistant_logs
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Grant access to authenticated users
GRANT SELECT, INSERT, UPDATE ON public.ai_assistant_logs TO authenticated;

-- Create an index for faster lookups
CREATE INDEX IF NOT EXISTS ai_assistant_logs_user_id_idx ON public.ai_assistant_logs (user_id);

-- Comments for better understanding
COMMENT ON TABLE public.ai_assistant_logs IS 'Stores interactions between users and the AI assistant';
COMMENT ON COLUMN public.ai_assistant_logs.user_message IS 'The message sent by the user';
COMMENT ON COLUMN public.ai_assistant_logs.assistant_message IS 'The response generated by the AI';
COMMENT ON COLUMN public.ai_assistant_logs.user_type IS 'Whether the user is a startup, investor, or unknown';
COMMENT ON COLUMN public.ai_assistant_logs.rating IS 'Optional user rating of the AI response (1-5)'; 